### PR TITLE
fix(web): added responsiveness for both authentication pages with minor routing functions

### PR DESCRIPTION
**Pull request by PonPonc**
This creates a draft layout of the authentication pages, login and logout pages with minor responsiveness to different screen sizes.

### CODE REVIEW

**Comment by Katteu** [comment]
@PonPonc resolve conflict please

**Review by Katteu — CHANGES_REQUESTED** [review]
**LOGIN PAGE:**
Follow newly created on Figma:
image

To be changed:
1. Add padding on input and change text color
image

2. Make these elements go up a bit similar to what is on Figma but keep the height
image

3. Add hover effect in button (just make the opacity not 100% lang siguro no need to change color, just darken it a bit) and also in the "Forgot Password?" text

4. At the 1024px breakpoint try to make the padding-y of the button bigger
image

5. Try to make the fonts a little bit bigger on the 1024px breakpoint but if it will break then no need ra
image

**FORGOT PASSWORD PAGE**
1. Add a little bit of padding-y sa button and add hover effect 
image

2. Add padding-x or padding-left sa input (up to you)
image

3. Add hover effect pud sa back button

4. I suggest to add spacing sa left between the left section and the back arrow during 1024px breakpoint

image

**Comment by FranzGwapo** [comment]
**LOGIN PAGE**
- Adjust gaps on "Streamline your costs..." in xl
image

- Adjust button padding left and right
image

```import { GiSmartphone } from "react-icons/gi";
<GiSmartphone />
```
- Use GiSmartphone on the smartphone icon
image

**FORGOT PASSWORD PAGE**
- Make **Forgot Password** word on the left bold
- Make "Enter pertinent details..." word on the left light

- Make "Forgot Password" word on the right font color black
- Font size of Email Address and Employee Number font-light and 24px(try)
- Reset Password button text-semibold

**Comment by PonPonc** [comment]
Did all changes especially with 1024px font resize.

**Review by FranzGwapo — APPROVED** [review]
lgtm

**Review by Katteu — APPROVED** [review]

**Pull request merged**
