### PR TITLE
fix(web): logout page button cursor-pointer fix and minor on hover animation

### PR DESCRIPTION
**Pull request by PonPonc**
feat: added routing for the authentication and created UI for logout

### CODE REVIEW

**Comment by Katteu** [comment]
@PonPonc  please ko fix merge conflict

**Review by hen-exe — APPROVED** [review]
LGTM

**Review by Katteu — CHANGES_REQUESTED** [review]
**Changes Requested:**
Responsiveness issues below breakpoint 2xl (1280px)
image

- Let image occupy the majority of the space sa white section

Change "login Page" to "Login Page"
image

**Review by Katteu — APPROVED** [review]
lgtm

**Pull request merged**
