### PR TITLE
feat(web): fix: added user management page, user creation page, and modals

### PR DESCRIPTION
**Pull request by hen-exe**
**Main User Management Page**
image

**User Creation Page**
image

### CODE REVIEW

**Review by Katteu — CHANGES_REQUESTED** [review]
**Changes Requested:**
- cursor pointer on tabs
- add font-lato
- change tab text to black
- add drop shadow to tabs
- make border colors and thickness same sa Figma
- add responsiveness
- link modals

**Comment by Katteu** [comment]
@hen-exe change the sidebar, please merge conflicts

**Comment by hen-exe** [comment]
image

**Review by Katteu — CHANGES_REQUESTED** [review]
- Border width
- Picture on User Create set to div background
- occupy the space on user create inputs
- fix responsiveness

**Comment by Katteu** [comment]
Waiting for @FranzGwapo 's commit

**Review by FranzGwapo — APPROVED** [review]
lgtm

**Review by Katteu — APPROVED** [review]
lgtm

**Pull request merged**
